### ISSUE TITLE
Account (trial)

### ISSUE THREAD

**Issue by faiyaz-libscr** [somleng/somleng#1488]
Hi, i am trying to deploy the full stack somleng production version using my own domain on AWS using terrraform. How to remove the limitations from account?

thanks

**Comment by dwilkie** [comment]
Hi,

We recommend reading the [Getting Started Guide](https://www.somleng.org/docs.html#getting-started), getting familiar with Somleng using a trial account and then optionally getting it running on your local machine, before trying to deploy Somleng to your own AWS.

Deploying Somleng to AWS is no easy feat even with Terraform, however we also offer professional services around Somleng. Feel free to reach out to me at dwilkie@somleng.org for more information.
